# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='u_type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
