# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20160119_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerproduct',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='sellerproduct',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=9),
            preserve_default=False,
        ),
    ]
